name: Release

on:
  push:
    branches:
      - master
      - beta

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Node and npm version
        run: node -v && npm -v

      - name: Install dependencies
        uses: npm ci

      - name: Release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: npm run semantic-release

      - name: Beta Release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: npm run semantic-release
